spring:
  datasource:
    url: jdbc:mysql://localhost:3306/production
    username : prod_user
    password : 171225
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa:
    database-platform : org.hibernate.dialect.MySQLDialect